version: '3.7'
services:
  web-project-tomcat:
    image: tomcat:10.1.18-jre17
    volumes:
      - ./tomcat/webapps/:/usr/local/tomcat/webapps/
    environment:
      TZ: Asia/Shanghai
    ports:
      - '8080:8080'
