version: '3.7'
services:
  web-project-tomcat:
    image: tomcat:10
    volumes:
      - ./tomcat/webapps/:/usr/local/tomcat/webapps/
    environment:
      TZ: Asia/Shanghai
    ports:
      - '80:8080'
